import type { Song, Playlist, Artist } from "@/types"

export const mockSongs: Song[] = [
  {
    id: "1",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: 203,
    thumbnail: "/neon-city-night-synthwave-album-cover.jpg",
    source: "youtube",
  },
  {
    id: "2",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: 223,
    thumbnail: "/disco-retro-futuristic-pop-album-cover.jpg",
    source: "youtube",
  },
  {
    id: "3",
    title: "Save Your Tears",
    artist: "The Weeknd",
    album: "After Hours",
    duration: 215,
    thumbnail: "/dark-emotional-portrait-album-art.jpg",
    source: "youtube",
  },
  {
    id: "4",
    title: "Stay",
    artist: "The Kid LAROI, Justin Bieber",
    album: "F*CK LOVE 3",
    duration: 141,
    thumbnail: "/colorful-pop-summer-vibes-album.jpg",
    source: "youtube",
  },
  {
    id: "5",
    title: "Heat Waves",
    artist: "Glass Animals",
    album: "Dreamland",
    duration: 238,
    thumbnail: "/psychedelic-dreamy-hazy-album-cover.jpg",
    source: "youtube",
  },
  {
    id: "6",
    title: "Peaches",
    artist: "Justin Bieber",
    album: "Justice",
    duration: 198,
    thumbnail: "/warm-sunset-peach-tones-album-art.jpg",
    source: "youtube",
  },
  {
    id: "7",
    title: "Montero",
    artist: "Lil Nas X",
    album: "MONTERO",
    duration: 137,
    thumbnail: "/vibrant-pink-fantasy-bold-album-cover.jpg",
    source: "youtube",
  },
  {
    id: "8",
    title: "Good 4 U",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    duration: 178,
    thumbnail: "/punk-rock-teenage-angst-album-cover.jpg",
    source: "youtube",
  },
  {
    id: "9",
    title: "Industry Baby",
    artist: "Lil Nas X, Jack Harlow",
    album: "MONTERO",
    duration: 212,
    thumbnail: "/bold-gold-pink-powerful-album-cover.jpg",
    source: "youtube",
  },
  {
    id: "10",
    title: "drivers license",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    duration: 242,
    thumbnail: "/emotional-melancholic-rainy-album-art.jpg",
    source: "youtube",
  },
  {
    id: "11",
    title: "Shivers",
    artist: "Ed Sheeran",
    album: "=",
    duration: 207,
    thumbnail: "/colorful-abstract-pattern-album-cover.jpg",
    source: "youtube",
  },
  {
    id: "12",
    title: "Easy On Me",
    artist: "Adele",
    album: "30",
    duration: 224,
    thumbnail: "/elegant-black-white-portrait-album.jpg",
    source: "youtube",
  },
]

export const mockPlaylists: Playlist[] = [
  {
    id: "pl1",
    title: "Today's Top Hits",
    description: "Las canciones más escuchadas del momento",
    thumbnail: "/trending-music-vibrant-neon-playlist-cover.jpg",
    songCount: 50,
    source: "youtube",
    songs: mockSongs.slice(0, 5),
  },
  {
    id: "pl2",
    title: "Chill Vibes",
    description: "Música para relajarte",
    thumbnail: "/relaxing-sunset-beach-calm-playlist-cover.jpg",
    songCount: 35,
    source: "youtube",
    songs: mockSongs.slice(2, 6),
  },
  {
    id: "pl3",
    title: "Workout Mix",
    description: "Energía para tu entrenamiento",
    thumbnail: "/energetic-gym-workout-powerful-playlist-cover.jpg",
    songCount: 40,
    source: "youtube",
    songs: mockSongs.slice(4, 9),
  },
  {
    id: "pl4",
    title: "Late Night Drive",
    description: "Perfecta para manejar de noche",
    thumbnail: "/neon-city-night-synthwave-album-cover.jpg",
    songCount: 28,
    source: "youtube",
    songs: mockSongs.slice(0, 4),
  },
  {
    id: "pl5",
    title: "Pop Rising",
    description: "Los nuevos éxitos del pop",
    thumbnail: "/disco-retro-futuristic-pop-album-cover.jpg",
    songCount: 45,
    source: "youtube",
    songs: mockSongs.slice(5, 10),
  },
  {
    id: "pl6",
    title: "Mood Booster",
    description: "Canciones para subir el ánimo",
    thumbnail: "/colorful-pop-summer-vibes-album.jpg",
    songCount: 60,
    source: "youtube",
    songs: mockSongs.slice(1, 7),
  },
  {
    id: "pl7",
    title: "Acoustic Covers",
    description: "Versiones acústicas de tus favoritas",
    thumbnail: "/warm-sunset-peach-tones-album-art.jpg",
    songCount: 42,
    source: "custom",
    songs: mockSongs.slice(3, 8),
  },
  {
    id: "pl8",
    title: "Focus Flow",
    description: "Música para concentrarte",
    thumbnail: "/psychedelic-dreamy-hazy-album-cover.jpg",
    songCount: 55,
    source: "custom",
    songs: mockSongs.slice(0, 6),
  },
]

export const mockArtists: Artist[] = [
  {
    id: "art1",
    name: "The Weeknd",
    image: "/dark-emotional-portrait-album-art.jpg",
    monthlyListeners: 85000000,
    isFollowing: false,
    topSongs: mockSongs.filter((s) => s.artist.includes("Weeknd")),
  },
  {
    id: "art2",
    name: "Dua Lipa",
    image: "/disco-retro-futuristic-pop-album-cover.jpg",
    monthlyListeners: 65000000,
    isFollowing: true,
    topSongs: mockSongs.filter((s) => s.artist.includes("Dua Lipa")),
  },
  {
    id: "art3",
    name: "Olivia Rodrigo",
    image: "/punk-rock-teenage-angst-album-cover.jpg",
    monthlyListeners: 55000000,
    isFollowing: false,
    topSongs: mockSongs.filter((s) => s.artist.includes("Olivia")),
  },
  {
    id: "art4",
    name: "Lil Nas X",
    image: "/vibrant-pink-fantasy-bold-album-cover.jpg",
    monthlyListeners: 45000000,
    isFollowing: false,
    topSongs: mockSongs.filter((s) => s.artist.includes("Lil Nas X")),
  },
  {
    id: "art5",
    name: "Justin Bieber",
    image: "/colorful-pop-summer-vibes-album.jpg",
    monthlyListeners: 75000000,
    isFollowing: true,
    topSongs: mockSongs.filter((s) => s.artist.includes("Justin Bieber")),
  },
  {
    id: "art6",
    name: "Ed Sheeran",
    image: "/colorful-abstract-pattern-album-cover.jpg",
    monthlyListeners: 82000000,
    isFollowing: false,
    topSongs: mockSongs.filter((s) => s.artist.includes("Ed Sheeran")),
  },
]

export const mockRecommendations = mockSongs.slice(3, 8)
export const mockTrending = mockSongs.slice(0, 6)
export const mockRecent = mockSongs.slice(2, 7)

export const mockLyrics = {
  synced: true,
  lines: [
    { time: 0, text: "I've been tryna call" },
    { time: 4, text: "I've been on my own for long enough" },
    { time: 8, text: "Maybe you can show me how to love, maybe" },
    { time: 12, text: "I'm going through withdrawals" },
    { time: 16, text: "You don't even have to do too much" },
    { time: 20, text: "You can turn me on with just a touch, baby" },
    { time: 24, text: "I look around and Sin City's cold and empty" },
    { time: 28, text: "No one's around to judge me" },
    { time: 32, text: "I can't see clearly when you're gone" },
    { time: 36, text: "I said, ooh, I'm blinded by the lights" },
    { time: 40, text: "No, I can't sleep until I feel your touch" },
    { time: 44, text: "I said, ooh, I'm drowning in the night" },
    { time: 48, text: "Oh, when I'm like this, you're the one I trust" },
  ],
}
